---
namespace: serverscom
name: sc_api
version: 0.2.0
readme: README.md
authors:
  - George Shuklin <george.shuklin@gmail.com>
  - Volodymyr Rudniev <rudnev.vv@gmail.com>
description: Collection of modules to work with Servers.com API
license:
  - GPL-3.0-or-later
tags: [cloud]
dependencies: {}
repository: https://github.com/serverscom/serverscom-ansible
documentation: https://github.com/serverscom/serverscom-ansible/README.md
homepage: https://github.com/serverscom/serverscom-ansible
issues: https://github.com/serverscom/serverscom-ansible/issues
