#!/usr/bin/env bash
ansible-test integration --python=3.8 sc_baremetal_locations_info sc_baremetal_servers_info sc_cloud_computing_flavors_info sc_cloud_computing_images_info sc_cloud_computing_instance_info sc_cloud_computing_instances_info sc_cloud_computing_openstack_credentials sc_cloud_computing_regions_info sc_dedicated_server_info sc_dedicated_server_reinstall_quick
